module.exports = {
  'RouterHx Test': function(client) {
    client
      .url('localhost:2000')
      .waitForElementVisible('body', 1000)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#contents', 'dynamic')
        .assert.containsText('#footer', 'global after')
      .click('h1 a').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#sub-header', 'local before')
        .assert.containsText('#contents', 'index')
        .assert.containsText('#sub-footer', 'local after')
        .assert.containsText('#footer', 'global after')
      .click('#index').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#sub-header', 'local before')
        .assert.containsText('#contents', 'index')
        .assert.containsText('#sub-footer', 'local after')
        .assert.containsText('#footer', 'global after')
      .click('#greet0').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#sub-header', 'local before')
        .assert.containsText('#contents', 'morning')
        .assert.containsText('#sub-footer', 'local after')
        .assert.containsText('#footer', 'global after')
      .click('#greet1').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#sub-header', 'local before')
        .assert.containsText('#contents', 'hello')
        .assert.containsText('#sub-footer', 'local after')
        .assert.containsText('#footer', 'global after')
      .click('#micro0').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#contents', 'micro')
        .assert.containsText('#footer', 'global after')
      .click('#micro1').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#contents', 'micro1')
        .assert.containsText('#footer', 'global after')
      .click('#micro2').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#contents', 'micro2')
        .assert.containsText('#footer', 'global after')
      .click('#notfound').pause(50)
        .assert.containsText('#header', 'global before')
        .assert.containsText('#contents', 'not found')
        .assert.containsText('#footer', 'global after')
      .click('#check-local-dispatch').pause(50)
        .assert.containsText('#event-dispatch-global-before', 'global before dispatched')
        .assert.containsText('#event-dispatch-global-after', 'global after dispatched')
        .assert.containsText('#event-dispatch-before', '')
        .assert.containsText('#event-dispatch-after', '')
      .click('#check-global-dispatch').pause(50)
        .assert.containsText('#event-dispatch-global-before', 'global before dispatched')
        .assert.containsText('#event-dispatch-global-after', 'global after dispatched')
        .assert.containsText('#event-dispatch-before', 'before dispatched')
        .assert.containsText('#event-dispatch-after', 'after dispatched')
      .end();
  }
}